namespace Chef.Common.Types
{
    public enum JournalBookTypeCodes
    {
        ManualDoubleEntryJournal = 100,
        InterBranchTransactionJournal = 101,
        YearClosingJournal = 102,
        GLCurrencyRevaluation = 103,
        Openingbalancejournal = 104,
        RecurringandReversalJournal = 105,

        CustomerCreditNote = 200,
        CustomerCreditNoteAllocation = 201,
        CustomerDepositAllocation = 202,
        CustomeronAccountReceiptsAllocation = 203,
        CustomerAdvanceReceipt = 204,
        CustomerDepositReceipt = 205,
        SupplierAdvanceRefund = 206,
        SupplierDepositRefund = 207,
        ManualSalesInvoiceJournal = 208,
        TradeSalesInvoices = 209,
        CustomerReceiptAgainstInvoices = 210,
        CustomerAdvanceAllocation = 211,
		CustomerOnAccountReceipt = 212,
        CustomerAdvanceRefundAllocation = 213,
        CustomerDepositRefundAllocation =214,


        IntercompanyTransactionJournal = 300,
        BankReconciliation = 301,
        ARAPBalanceWriteOff = 302,
        ARAPKnockOff = 303,
        BadDebtsWriteOff = 304,
        SupplierCurrencyRevaluation = 305,
        CustomerCurrencyRevaluation = 306,
        BanktoBankTransfers = 307,

        PettyCashPayments = 400,
        PettyCashReimbursement = 401,

        SupplierInvoiceWithoutPOMatching = 500,
        SupplierPaymentAgainstInvoices = 501,
        SupplierAdvancePayment = 502,
        SupplierDepositPayment = 503,
        CustomerRefundofDeposit = 504,
        CustomerRefundofAdvance = 505,
        SupplierOnAccountPayment = 506,
        SupplierCreditNote = 507,
        SupplierOnAccountPaymentAllocation = 508,
        SupplierDepositAllocation = 509,
        SupplierAdvanceAllocation = 510,
        SupplierCreditNoteAllocation = 511,
        SupplierInvoiceWithPOMatching = 512,

        PurchaseModuleIntegration = 600,
        GoodsReceiptsIntegration = 601,
        GoodsReturnIntegration = 602,
        InventoryModuleIntegration = 603,
        InventoryAdjustmentIntegration = 604,
        InventoryCycleCountingIntegration = 605,
        WarehouseTransferIntegration = 606,
        ManufacturingModuleIntegration = 607,
        MaterialIssueIntegration = 608,
        ManpowerTimesheetIntegration = 609,
        // ManpowerTimesheetIntegration = 610,
        MachineTimesheetIntegration = 611,
        ProductionClosingIntegration = 613,
        OverheadAbsorptionIntegration = 612,
        SalesModuleIntegration = 614,
        SalesIssueIntegration = 616,
        SalesInvoicingIntegration = 617,
        SalesReturnIntegration = 618,
        MatchandApproval = 619,

        CashCollectionAccount = 700,
        OnAccountRepaymentToCustomers = 702,
        CashSaleInvoice = 800,
        CashSaleReturn = 801,
        HRMSIntegration = 802,
        PettyCashAdvance = 803
    }
}